[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, fails build when a category is below a threshold
[plugins.inputs.thresholds]
	# This is being lowered to allow for a bit of margin for the "Background and
	# Foreground colors do not have a sufficient contrast ratio." error. I can't
	# change the colors of the app, and so I can't fix this error
	accessibility = 0.9
	best-practices = 1.0
	# The value is lowered to this to allow the "incorrect canonical URL" error to exist
	seo = 0.92